pipeline:
  name: GitEx Example
  identifier: GitEx_Example
  projectIdentifier: Git_Sync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: "This is a test."
        type: Deployment
        spec:
          deploymentType: Ssh
          service:
            serviceRef: myapp
          environment:
            environmentRef: qa
            deployToAll: false
            infrastructureDefinitions:
              - identifier: pdc
                inputs:
                  identifier: pdc
                  type: Pdc
                  spec:
                    connectorRef: <+input>
                    credentialsRef: <+input>
          execution:
            steps:
              - stepGroup:
                  name: Phase
                  identifier: Phase
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                      maxConcurrency: 1
                      partitionSize: 1
                      unit: Count
                  steps:
                    - stepGroup:
                        name: Phase Group
                        identifier: phase_group
                        strategy:
                          repeat:
                            items: <+repeat.partition>
                        steps:
                          - step:
                              name: Deploy
                              identifier: Deploy
                              timeout: 10m
                              template:
                                templateRef: account.Default_Install_War_Bash
                                templateInputs:
                                  type: Command
                                  spec:
                                    environmentVariables:
                                      - name: DestinationDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>
            rollbackSteps:
              - stepGroup:
                  name: Phase
                  identifier: Phase
                  strategy:
                    repeat:
                      items: <+stage.output.hosts>
                      maxConcurrency: 1
                      partitionSize: 1
                      unit: Count
                  steps:
                    - stepGroup:
                        name: Phase Group Rollback
                        identifier: phase_group_rollback
                        strategy:
                          repeat:
                            items: <+repeat.partition>
                        steps:
                          - step:
                              name: Rollback
                              identifier: Rollback
                              timeout: 10m
                              template:
                                templateRef: account.Default_Install_War_Bash
                                templateInputs:
                                  type: Command
                                  spec:
                                    environmentVariables:
                                      - name: DestinationDirectory
                                        type: String
                                        value: $HOME/<+service.name>/<+env.name>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
