pipeline:
  name: gitsync
  identifier: gitsync
  projectIdentifier: Git_Sync
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: gitsync
        identifier: gitsync
        description: ""
        type: Deployment
        spec:
          serviceConfig:
            serviceRef: foo
            serviceDefinition:
              spec:
                variables: []
              type: Kubernetes
          infrastructure:
            environmentRef: <+input>
            infrastructureDefinition:
              type: KubernetesDirect
              spec:
                connectorRef: <+input>
                namespace: <+input>
                releaseName: release-<+INFRA_KEY>
            allowSimultaneousDeployments: false
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: script
                  identifier: script
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo "hello"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
