apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vanilla-k8s-app1
spec:
  generators:
  - git:
      repoURL: https://github.com/wings-software/harness-docs.git
      revision: HEAD
      files:
      - path: "gitops-appset-ex/vanilla-k8s/app1/*/*/config.json"
  template:
    metadata:
      name: 'vanilla-k8s-app1-{{cluster.name}}'
    spec:
      project: b062fb30
      source:
        repoURL: https://github.com/wings-software/harness-docs.git
        targetRevision: '{{releaseTag}}'
        path: "gitops-appset-ex/vanilla-k8s/apps/app1/{{pathSuffix}}"
      destination:
        server: '{{cluster.address}}'
        namespace: default
      syncPolicy:
        automated: {}
