apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-k8s-deployment-qa
  labels:
    app: nginx
    apptype: vanilla-k8s
    env: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: qa
      apptype: vanilla-k8s
  template:
    metadata:
      labels:
        app: nginx
        env: qa
        apptype: vanilla-k8s
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
